import { ArtItem } from './types';

export const ART_PIECES: ArtItem[] = [
  {
    id: 1,
    title: "Cosmic Drift",
    artist: "Orion Pax",
    description: "A mesmerizing depiction of nebulae colliding in the vast expanse of space, rendered in vibrant, electric hues. This piece captures the chaotic beauty of creation.",
    price: 450,
    imageUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&q=80&auto=format&fit=crop",
    year: 2023,
  },
  {
    id: 2,
    title: "Silent Metropolis",
    artist: "Jane Doe",
    description: "A hauntingly beautiful cityscape at midnight, bathed in the soft glow of neon lights and shrouded in a gentle fog. The silence is palpable, inviting introspection.",
    price: 620,
    imageUrl: "https://images.unsplash.com/photo-1507530658428-9b8f3a3a3f3b?w=800&q=80&auto=format&fit=crop",
    year: 2022,
  },
  {
    id: 3,
    title: "Forest's Breath",
    artist: "Leo Natura",
    description: "An impressionistic view of a sun-dappled forest floor, focusing on the interplay of light and shadow. The artist masterfully conveys the feeling of a cool, gentle breeze.",
    price: 380,
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80&auto=format&fit=crop",
    year: 2024,
  },
  {
    id: 4,
    title: "Geometric Soul",
    artist: "Alex Vector",
    description: "A complex array of geometric shapes and lines that form a surprisingly organic and emotional whole. This piece explores the structure of consciousness.",
    price: 710,
    imageUrl: "https://images.unsplash.com/photo-1604871009145-b013b398698f?w=800&q=80&auto=format&fit=crop",
    year: 2023,
  },
  {
    id: 5,
    title: "Ocean's Embrace",
    artist: "Marina Blue",
    description: "The raw power and serene beauty of the ocean captured in a single, dynamic frame. Swirls of deep blue and turquoise crash against a canvas of white foam.",
    price: 550,
    imageUrl: "https://images.unsplash.com/photo-1502675133393-6fad39883427?w=800&q=80&auto=format&fit=crop",
    year: 2021,
  },
  {
    id: 6,
    title: "Desert Bloom",
    artist: "Solara",
    description: "A stark desert landscape transformed by the rare and vibrant bloom of a single, resilient flower. A testament to life's tenacity in the harshest of environments.",
    price: 480,
    imageUrl: "https://images.unsplash.com/photo-1473580044384-9b92b6dd4469?w=800&q=80&auto=format&fit=crop",
    year: 2024,
  },
  {
    id: 7,
    title: "Chromatic Flow",
    artist: "KAI",
    description: "An abstract exploration of color theory, where fluid gradients blend and separate in a harmonious dance. This piece is pure visual energy.",
    price: 800,
    imageUrl: "https://images.unsplash.com/photo-1536968448145-4224b1a29c11?w=800&q=80&auto=format&fit=crop",
    year: 2023,
  },
  {
    id: 8,
    title: "Echoes of the Past",
    artist: "Historia",
    description: "A mixed-media piece that layers historical photographs with modern digital brushstrokes, creating a conversation between past and present.",
    price: 650,
    imageUrl: "https://images.unsplash.com/photo-1517594422361-5e3e8a302988?w=800&q=80&auto=format&fit=crop",
    year: 2022,
  },
  {
    id: 9,
    title: "Cybernetic Dreams",
    artist: "Alex Vector",
    description: "An exploration of artificial consciousness through a vibrant, digital lens.",
    price: 950,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
    year: 2024,
  },
  {
    id: 10,
    title: "Lunar Serenity",
    artist: "Orion Pax",
    description: "The quiet, tranquil surface of the moon under a sky of distant stars.",
    price: 420,
    imageUrl: "https://images.unsplash.com/photo-1444703686981-a3abbc4d42e2?w=800&q=80&auto=format&fit=crop",
    year: 2021,
  },
  {
    id: 11,
    title: "Urban Jungle",
    artist: "Jane Doe",
    description: "A striking contrast between brutalist architecture and overgrown nature.",
    price: 680,
    imageUrl: "https://images.unsplash.com/photo-1479839672679-a46483c0f748?w=800&q=80&auto=format&fit=crop",
    year: 2023,
  },
  {
    id: 12,
    title: "Autumn's Whisper",
    artist: "Leo Natura",
    description: "The gentle fall of golden leaves in a misty, enchanted forest.",
    price: 390,
    imageUrl: "https://images.unsplash.com/photo-1476842634003-7d387b428d9c?w=800&q=80&auto=format&fit=crop",
    year: 2022,
  },
   {
    id: 13,
    title: "Tidal Force",
    artist: "Marina Blue",
    description: "The immense power of the tides, captured in a swirling vortex of water and light.",
    price: 580,
    imageUrl: "https://images.unsplash.com/photo-1532372576221-45030700e31e?w=800&q=80&auto=format&fit=crop",
    year: 2024,
  },
  {
    id: 14,
    title: "Solar Flare",
    artist: "Solara",
    description: "An explosive burst of energy from the sun's surface, painted in fiery reds and oranges.",
    price: 750,
    imageUrl: "https://images.unsplash.com/photo-1614726353900-196d1c035613?w=800&q=80&auto=format&fit=crop",
    year: 2023,
  },
  {
    id: 15,
    title: "Pastel Dreams",
    artist: "KAI",
    description: "A soft, dreamlike landscape composed of gentle pastel colors and flowing shapes.",
    price: 480,
    imageUrl: "https://images.unsplash.com/photo-1569428034239-f9565f18a280?w=800&q=80&auto=format&fit=crop",
    year: 2022,
  },
  {
    id: 16,
    title: "Faded Memories",
    artist: "Historia",
    description: "A ghostly, ethereal piece that evokes a sense of nostalgia and lost time.",
    price: 610,
    imageUrl: "https://images.unsplash.com/photo-1526724395899-734a34b25abc?w=800&q=80&auto=format&fit=crop",
    year: 2021,
  },
    {
    id: 17,
    title: "Mountain's Majesty",
    artist: "Orion Pax",
    description: "A grand, imposing mountain peak piercing through a sea of clouds.",
    price: 720,
    imageUrl: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800&q=80&auto=format&fit=crop",
    year: 2024,
  },
  {
    id: 18,
    title: "Neon Pulse",
    artist: "Jane Doe",
    description: "The vibrant, rhythmic pulse of a city that never sleeps, captured in neon light trails.",
    price: 810,
    imageUrl: "https://images.unsplash.com/photo-1534313314376-a72013f364d2?w=800&q=80&auto=format&fit=crop",
    year: 2023,
  },
  {
    id: 19,
    title: "Crystalline Cave",
    artist: "Leo Natura",
    description: "A hidden underground world filled with glowing crystals and serene pools of water.",
    price: 530,
    imageUrl: "https://images.unsplash.com/photo-1560962382-79331534a690?w=800&q=80&auto=format&fit=crop",
    year: 2022,
  },
  {
    id: 20,
    title: "Abstract Mind",
    artist: "Alex Vector",
    description: "A visual representation of complex thought, with interconnected lines and explosive color.",
    price: 900,
    imageUrl: "https://images.unsplash.com/photo-1506241537212-2a2b500a424a?w=800&q=80&auto=format&fit=crop",
    year: 2024,
  },
];
